[project]
name = "opencv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "caer>=2.1.1",
    "matplotlib>=3.10.6",
    "opencv-contrib-python>=4.12.0.88",
    "requests>=2.32.5",
]
